CREATE TABLE TOUR (
    matour   VARCHAR(15) NOT NULL PRIMARY KEY,
    tentour  VARCHAR(25) NOT NULL
)

CREATE TABLE KHACHHANG  (
    makh INTEGER PRIMARY KEY AUTO_INCREMENT,
    matour VARCHAR(15) NOT NULL ,
    tenkh VARCHAR(35) NOT NULL ,
    sodt VARCHAR(11) NOT NULL ,
    soluong INTEGER NOT NULL ,
    thoigian DATETIME,
    FOREIGN KEY (matour) REFERENCES TOUR(matour)
)